/* ===== CONSTANTS ===== */
export const V = 0.3;          // voxel size
export const AW = 108;         // arena width  (X)  — 72×1.5
export const AL = 165;         // arena length (Z)  — 110×1.5
export const AH = 45;          // arena height (Y)  — 30×1.5
export const GW = 27;          // goal width        — 18×1.5
export const GH = 18;          // goal height       — 12×1.5
export const GD = 12;          // goal depth        — 8×1.5
export const BR = 2.25;        // ball radius
export const CHX = 1.05;       // car half-extents
export const CHY = 0.65;
export const CHZ = 2.05;
export const GRAV = -14.0;
export const C_ACC = 56;       // car acceleration
export const C_MAX = 500;      // car max speed
export const C_TURN = 3.4;     // car turn speed (rad/s)
export const C_GFRI = 0.945;   // car ground friction
export const C_AFRI = 0.985;   // car air friction
export const J_VEL = 14;       // jump velocity (reduced to ~60% of old 18)
export const J_CUT = 0.55;     // variable jump: velocity kept on quick release
export const ACCEL_RAMP_T = 0.4; // seconds to reach full acceleration
export const F_VEL = 23;       // flip impulse
export const F_DUR = 0.28;     // flip anim duration
export const B_ACC = 78;       // boost acceleration
export const B_MAX = 800;
export const B_DRAIN = 0.65;
export const B_REGEN = 0.12;
export const B_REST = 0.82;    // ball restitution
export const W_REST = 0.85;    // wall restitution
export const BG_FRI = 0.978;   // ball ground friction
export const BA_FRI = 0.997;   // ball air friction
export const F_MULT = 1.8;     // flip hit multiplier
export const C_MASS = 5;
export const BL_MASS = 1;
export const GOAL_CD = 2.0;    // goal cooldown seconds
export const RAMP_RADIUS = 30;  // wall ramp radius for wall riding
